### ISSUE TITLE
WorldEdit toggle command

### ISSUE THREAD

**Issue by jyhsu2000** [IntellectualCrafters/PlotSquared#90]
If I don't have "plots.weanywhere",
I can only use WorldEdit in every plots belongs me.
This works well.

But, if I have "plots.weanywhere",
I can toggle WorldEdit mode in the following two
- can use WorldEdit at anywhere
- can use WorldEdit only in the plot where I run this command (not include other plots belongs me)

I think this is not convenience to use.
Would you like to make it toggle in these two modes by using this command?
- can use WorldEdit at anywhere
- can use WorldEdit in every plots belongs me. (Just like player without "plots.weanywhere")

**Comment by boy0001** [comment]
- Duplicate of #88
 - Already a feature:
http://www.spigotmc.org/resources/plotsquared.1177/update?update=10534

**Comment by jyhsu2000** [comment]
Sorry.
But it's not a duplicate issue.
This is a issue after trying v2.5.7.
Please focus on second mode.
There is a little different between two.

In v2.5.7
After I use **/p weanywhere** and update mask,
I can only use WorldEdit in the plot in where I use the command.
But I can **NOT** use WorldEdit in other plots belongs me.

What we hope is that there is a mode
let we use WorldEdit in "**every plots belongs me**" but not only the plot where I use the command.

Sorry for bad explanation.
For example,
In the mode **weanywhere**, I can use WorldEdit anywhere.
In the other mode, see the table below.

|  | The plot I use the command | other plots belongs me | other's plots | road
| --- | --- | --- | --- | --- |
| v2.5.7 | O | X | - | X |
| we hope | O | O | - | X |

**Comment by boy0001** [comment]
Thanks for the further clarification. I kinda just skim through these things. It's an issue with you having the bypass permission, the plugin doesn't think it should update your mask at all.

I'll add some more checks soon, which should fix it.

**Comment by boy0001** [comment]
fixed in f119f6996d4df0d6510a775cc04fcf9f6d111d24

**Comment by jyhsu2000** [comment]
I tried v2.5.8 and v2.5.10
I used **/p weanywhere** to turn to **limit mode**.
WE mask works well.
But once I enter the plots **owned by others**,
WE mask has been cleared.
This mean that when I walk through others plot, it turn to **weanywhere mode** forcibly.
Is it a bug?

**Comment by boy0001** [comment]
Bug? Undocumented feature?
I will either document or fix the issue soon.

**Comment by jyhsu2000** [comment]
I think it's a bug.
I tried it again in v2.5.10.
Take a look at the following video.
You will know this issue more clearly.
http://youtu.be/3asW8toKzYE

**Comment by jyhsu2000** [comment]
`cf43c74` didn't fix this bug.
In v2.5.11
It just back to the bug of v2.5.7 like [this](https://github.com/IntellectualCrafters/PlotSquared/issues/90#issuecomment-69557836)

**Comment by boy0001** [comment]
Attempt 3:
http://www.spigotmc.org/resources/plotsquared.1177/update?update=12232

**Comment by jyhsu2000** [comment]
In fact, more terrible...

1.
In no-limit mode, I can use WE everywhere, this works fine.
But after I use `/p wea`

|     | plots belongs me | plots belongs other | unowned plots | road |
| --- | --- | --- | --- | --- |
| v2.6 | O | X | X | X |
| hope | O | O | - | X |
Maybe there is a little wrong when using WE in other's plots ?
Or just you don't want anyone use WE in other's plots in limit mode ?

2.
When I stand in plots with flag `no-worldedit:true`
`/p wea` can not work well.

| mode | no-worldedit | ---action---> | new mode | wrong? |
| --- | --- | --- | --- | --- |
| no-limit | true | `/p wea` | no-limit | <-wrong |
| limit | true | `/p wea` | no-limit | - |
|   |
| no-limit | unset | `/p flag add no-worldedit true` | no-limit | - |
| limit | unset | `/p flag add no-worldedit true` | limit | <-wrong (mask can not be auto update when I entry my other plots) |
| no-limit | true | `/p flag remove no-worldedit` | no-limit | - |
| limit | true | `/p flag remove no-worldedit` | no-limit | <- little wrong (mask update after re-entry) |

**Comment by boy0001** [comment]
It behaves as expected in the latest release.

In limit mode, you worldedit in places you have permission for, in bypass mode, you bypass everything (including the flags)

As for the mask not auto-updating, I've been testing and it seems to update fine with the latest version.
